set guicursor=
set relativenumber
set hidden
set noerrorbells
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set nowrap
set noswapfile
set nobackup
set undofile
set incsearch
set scrolloff=4
set colorcolumn=80
set termguicolors
set shortmess+=c
set hlsearch
set title
set titlestring=%t
set notimeout ttimeout ttimeoutlen=0
set numberwidth=3
set nostartofline
set mouse=n
set ignorecase
set smartcase
set splitright
set splitbelow
set noshowmode
